services:                              # Contenedores
  db:                                  # Nombre interno del servicio
    image: postgres:16
    container_name: mi_postgres
    restart: always                    # Reiniciar automaticamente si el servidor se reinicia

    environment:                        #Variables del entorno que configuran POSTGRESQL
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mi_db               #Nombre de base de datos inicial

    ports:
      - "5432:5432"                    #PORT_HOST:PORT_CONTENEDOR

    volumes:
      - postgres_data:/var/lib/postgresql/data  #Volume_Host : Folder interno donde Postgres guarda datos

volumes:
  postgres_data:
